### ISSUE TITLE
(Ali) As a developer, I would like to implement 'speech to text' component in order to use in the system

### ISSUE THREAD

**Issue by tubanury** [aligungr/Communica-p-tion#17]
Almost every Android device has a built-in Speech-To-Text API that is provided by operating system. We should use that native API for Speech-To-Text operations, no need to rely on some commercial APIs.

The API is accessable by SpeechRecognizer class.
(see https://developer.android.com/reference/android/speech/SpeechRecognizer)

However since we use Unity, instead of Native Android, we must first implement many bridge, and/or proxy like architecture using AndroidJavaClass, AndroidJavaObject, AndroidJavaProxy and related functionalities that are provided by Unity Engine.

Then we can use native SpeechRecognizer class from Unity.

Here is the high level overview of the subsystem:

![system](https://user-images.githubusercontent.com/25206055/72834818-a2ab8000-3c9a-11ea-8538-84f1fed73107.png)

**Comment by aligungr** [comment]
Currently automatic language detection for speech recogniation seems impossible

See these:
https://stackoverflow.com/questions/18449062/detect-language-from-recognizerintent
https://stackoverflow.com/questions/48594731/auto-detect-speech-recognition-language
https://stackoverflow.com/questions/33910920/android-detect-speech-recognition-language
