### ISSUE TITLE
(Planning) As a developer, I would like to create an architectural overall diagram for the system showing the components and their event/API intersections.

### ISSUE THREAD

**Issue by tubanury** [aligungr/Communica-p-tion#2]
(# references the issue)

# Highlevel
![AWS Web App Structural Flow-3](https://user-images.githubusercontent.com/30345525/72830660-39c00a00-3c92-11ea-809b-bc9c5a87d873.png)
**Component | Related to**
11 | Mobile Application
12 | Mobile Application
13 | Settings
14 | Text Replacement
15 | Settings
17 | 11,12,Mobile Application
19 | 36
22 | 36
23 | Text Replacement
24 | Text Replacement
35 | Mobile Application
36 | 11,12,Mobile Application
38 | Text Replacement
AR Glass | 11, 12, 14, 23, 24, 35, 38
Mobile Phone | 11, 12, 14, 23, 35, 38

## Speech to Text Component Detailed Structural Flow
![AWS Web App Structural Flow-6](https://user-images.githubusercontent.com/30345525/72763566-66721400-3bf5-11ea-824a-c9dad2658c74.png)
## Language Recognition Component Detailed Structural Flow
![AWS Web App Structural Flow-5](https://user-images.githubusercontent.com/30345525/72763532-3dea1a00-3bf5-11ea-8b69-0a873c2175f1.png)
## Settings Component Detailed Structural Flow
![AWS Web App Structural Flowed-3](https://user-images.githubusercontent.com/30345525/72787010-10768e00-3c40-11ea-9328-a84131183ec9.png)

**Comment by beyzaaltuntas** [comment]
After the issues are assigned, here are the owners of each component:
![AWS Web App Structural Flow-3 copy](https://user-images.githubusercontent.com/30345525/72753830-03718480-3bd7-11ea-81dc-62a3cfb8b100.png)
Tuba => #7, #23
Dilara => #8, #14
Semih => #3, #4, #9, #12
Ali => #14, #24, #5
Beyza => #6, #11, #13, #24
