### ISSUE TITLE
(Planning) Determine tools and programming languages for project.

### ISSUE THREAD

**Issue by tubanury** [aligungr/Communica-p-tion#3]
We should determine tools, technologies, and programming languages to use in the project.

**Comment by beyzaaltuntas** [comment]
Decisions on this matter are as follows:
- Unity was selected as development environment.
- C# was chosen as programming language for entire project.
- AR glasses and Android OS were determined as compatible platforms.
- AR glasses which taken from HAVELSAN Augmented Reality Team, will be used during project development.
- Yandex's translate API was selected for translation functionalities.
- Android Native API was selected for speech to text functionalities.
- Vuforia framework will be used as AR functionalities.
